var html = 
   ['<div id="mainMenuContainer">',
    	'<div id="mainMenu">',
    		'<h3>Architecture</h3>',
			'<ul>',
				'<li><a href="architecture_overview.htm">Overview</a></li>',
				'<li><a href="architecture_resolution.htm">Resolution</a></li>',
			'</ul>',    		
			'',
			'<h3>XIMPEL Introduction</h3>',
			'<ul>',
				'<li><a href="playlist_introduction.htm">Introduction</a></li>',
				'<li><a href="playlist_subjects.htm">Subjects</a></li>',
				'<hr />',
				'<li><a href="playlist_media_types.htm">Media Types</a></li>',
				'<li><a href="playlist_video.htm">Video</a></li>',
				'<li><a href="playlist_audio.htm">Audio</a></li>',
				'<li><a href="playlist_image.htm">Image</a></li>',
				'<li><a href="playlist_youtube.htm">Youtube</a></li>',
				'<li><a href="playlist_iframe.htm">iFrame</a></li>',
				'<li><a href="playlist_filler.htm">Filler</a></li>',
				'<hr />',
				'<li><a href="playlist_overlays.htm">Overlays</a></li>',
				'<li><a href="playlist_questions.htm">Questions</a></li>',
				'<li><a href="playlist_variables.htm">Variables / Scores</a></li>',
				'<hr />',
				'<li><a href="playlist_config.htm">Config</a></li>',
			'</ul>',
			'',
			'<h3>Getting Started</h3>',
			'<ul>',
				'<li><a href="getting_started_steps.htm">Step by step guide</a></li>',
				'<li><a href="getting_started_configuration_options.htm">XimpelApp options</a></li>',
			'</ul>',
			'',
			'<h3>Custom Media Types</h3>',
			'<ul>',
				'<li><a href="media_types_construction.htm">Building a media type</a></li>',
				'<li><a href="media_types_extra.htm">Extra</a></li>',
			'</ul>',
			'<h3>XIMPEL Advanced</h3>',
			'<ul>',
				'<li><a href="ximpel_analytics.htm">XIMPEL Analytics</a></li>',
				'<li><a href="playlist_terminal.htm">Terminal Media Type</a></li>',
				'<li><a href="ximpel_react.htm">XIMPEL React</a></li>',
			'</ul>',
			'<h3>Video Tutorials</h3>',
			'<ul>',
				'<li><a href="tutorial_positioning.htm">Positioning in XIMPEL</a></li>',
				'<li><a href="tutorial_specific_subject_testing.htm">Testing one subject in a long playlist</a></li>',
				'<li><a href="tutorial_what_is_a_file.htm">Simple presentation + code</a></li>',
				'<li><a href="tutorial_creating_presentation.htm">Live Stream: creating a complex XIMPEL presentation</a></li>',
			'</ul>',
			'<h3>Extra In-depth Documentation</h3>',
			'<ul>',
				'<li><a href="theses.htm">Master theses</a></li>',
			'</ul>',
		'</div>',
	'</div>',
   ].join('\n');

document.write( html );